// Generated by spring, do not touch!

package com.example.networksimulator;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
@RestController
public class NetworkSimulatorApplication {

    public static void main(String[] args) {
        SpringApplication.run(NetworkSimulatorApplication.class, args);
    }

}
