// Generated by spring, do not touch!

package com.example.networksimulator;

import org.json.simple.parser.JSONParser;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;


@SpringBootApplication
@RestController
public class NetworkSimulatorApplication {

    public static void main(String[] args) {
        SpringApplication.run(NetworkSimulatorApplication.class, args);
    }

    @GetMapping("/update-json")
    public @ResponseBody String getJson (@RequestParam(value = "Encoding") String encoding,
                                         @RequestParam(value = "FileName") String filename){
        FileParser parser = new FileParser(filename, encoding);

        return parser.refresh();
    }

}
